spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://board-mysql:3306/board
    username: root
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never

jwt:
  secret-key:

redis:
  host: redis-stack
  port: 6379
